# Generated by Django 6.0.3 on 2026-05-14 04:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_member_email'),
        ('dairymetrics', '0009_membermetrictransaction_departmentdailymetricsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailIntegrationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gmail', 'Gmail')], default='gmail', max_length=32)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('sender_name', models.CharField(blank=True, max_length=128)),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('client_secret', models.CharField(blank=True, max_length=255)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_uri', models.URLField(default='https://oauth2.googleapis.com/token')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MailRecipientGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_recipient_groups', to='accounts.department')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MailRecipientGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='mail.mailrecipientgroup')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_group_memberships', to='accounts.member')),
            ],
            options={
                'ordering': ['group__name', 'member__name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='mailrecipientgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='mail_recipient_groups', through='mail.MailRecipientGroupMember', to='accounts.member'),
        ),
        migrations.CreateModel(
            name='MailSendHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField(default=django.utils.timezone.localdate)),
                ('subject_snapshot', models.CharField(max_length=255)),
                ('body_snapshot', models.TextField(blank=True)),
                ('sent_to_snapshot', models.TextField(blank=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', '準備中'), ('sent', '送信済み'), ('failed', '失敗')], default='draft', max_length=16)),
                ('is_test', models.BooleanField(default=False)),
                ('is_resend', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_send_histories', to='accounts.department')),
                ('integration_setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_histories', to='mail.mailintegrationsetting')),
                ('recipient_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_histories', to='mail.mailrecipientgroup')),
                ('sender_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_mail_histories', to='accounts.member')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_send_histories', to='dairymetrics.membermetrictransaction')),
            ],
            options={
                'ordering': ['-activity_date', '-sent_at', '-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='mailrecipientgroupmember',
            constraint=models.UniqueConstraint(fields=('group', 'member'), name='unique_mail_group_member'),
        ),
    ]
