# Generated by Django 6.0.3 on 2026-05-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailsendhistory',
            name='error_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='mailsendhistory',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mailsendhistory',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
