# Generated by Django 6.0.3 on 2026-05-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_member_email'),
        ('mail', '0002_mailsendhistory_error_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailrecipientgroup',
            name='related_departments',
            field=models.ManyToManyField(blank=True, related_name='mail_recipient_group_links', to='accounts.department'),
        ),
    ]
