# Generated by Django 6.0.3 on 2026-05-20 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_member_email'),
        ('mail', '0003_mailrecipientgroup_related_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailDepartmentRouting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mail_routing', to='accounts.department')),
                ('recipient_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_routings', to='mail.mailrecipientgroup')),
            ],
            options={
                'ordering': ['department__code', 'id'],
            },
        ),
    ]
