# Generated by Django 6.0.2 on 2026-02-23 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('UN', 'UN'), ('WV', 'WV'), ('STYLE1', 'Style1'), ('STYLE2', 'Style2')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_links', to='accounts.member')),
            ],
            options={
                'unique_together': {('member', 'department')},
            },
        ),
    ]
