# Generated by Django 6.0.2 on 2026-02-23 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_department_alter_memberdepartment_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='default_reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_department_links', to='accounts.member'),
        ),
    ]
