# Generated by Django 6.0.2 on 2026-03-05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_member_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="password",
        ),
    ]

