# Generated by Django 6.0.2 on 2026-03-05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_member_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="login_id",
        ),
    ]
