# Generated by Codex on 2026-06-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_department_dashboard_visibility_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="un_activity_code",
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
