# Generated by Django 6.0.8 on 2026-08-15 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0012_member_un_activity_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(max_length=128)),
                ('normalized_name', models.CharField(editable=False, max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_activity_sites', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activity_sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['canonical_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ActivitySiteAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_name', models.CharField(max_length=128)),
                ('normalized_name', models.CharField(editable=False, max_length=128, unique=True)),
                ('source', models.CharField(choices=[('import', '過去データ取込'), ('proposal', '新規現場申請'), ('manual', '管理者登録')], default='manual', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='activity_sites.activitysite')),
            ],
            options={
                'ordering': ['alias_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ActivitySiteDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_site_links', to='accounts.department')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_links', to='activity_sites.activitysite')),
            ],
            options={
                'ordering': ['department__code', 'site__canonical_name'],
            },
        ),
        migrations.AddField(
            model_name='activitysite',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='activity_sites', through='activity_sites.ActivitySiteDepartment', to='accounts.department'),
        ),
        migrations.CreateModel(
            name='ActivitySiteProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_name', models.CharField(max_length=128)),
                ('normalized_name', models.CharField(editable=False, max_length=128)),
                ('status', models.CharField(choices=[('pending', '申請中'), ('approved', '承認済み'), ('merged', '既存現場へ統合'), ('rejected', '却下')], default='pending', max_length=16)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_site_proposals', to='accounts.department')),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_site_proposals', to=settings.AUTH_USER_MODEL)),
                ('resolved_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_proposals', to='activity_sites.activitysite')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_activity_site_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='activitysitedepartment',
            constraint=models.UniqueConstraint(fields=('site', 'department'), name='unique_activity_site_department'),
        ),
        migrations.AddIndex(
            model_name='activitysite',
            index=models.Index(fields=['is_active', 'canonical_name'], name='site_active_name_idx'),
        ),
        migrations.AddIndex(
            model_name='activitysiteproposal',
            index=models.Index(fields=['status', 'created_at'], name='site_prop_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='activitysiteproposal',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('department', 'normalized_name'), name='unique_pending_site_proposal'),
        ),
        migrations.AddConstraint(
            model_name='activitysiteproposal',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'rejected']), ('resolved_site__isnull', False), _connector='OR'), name='resolved_site_required_after_approval'),
        ),
    ]
