# Generated by Django 6.0.8 on 2026-08-15 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysiteproposal',
            name='resolved_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_proposals', to='activity_sites.activitysite'),
        ),
    ]
