# Generated by Django 6.0.3 on 2026-08-06 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0012_member_un_activity_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MosaicResultType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_success', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '結果',
                'verbose_name_plural': '結果',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MosaicTrialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'お試しモデル',
                'verbose_name_plural': 'お試しモデル',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MosaicVisitPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '来店目的',
                'verbose_name_plural': '来店目的',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MosaicInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_date', models.DateField(verbose_name='日付')),
                ('age_band', models.CharField(blank=True, max_length=32, verbose_name='年代')),
                ('party_type', models.CharField(blank=True, choices=[('single', '1人'), ('group', '複数')], max_length=16, verbose_name='人数区分')),
                ('stay_duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='滞在時間（分）')),
                ('needs', models.TextField(blank=True, verbose_name='ニーズ')),
                ('talk_summary', models.TextField(blank=True, verbose_name='トーク内容')),
                ('payment_amount', models.PositiveIntegerField(default=0, verbose_name='決済金額')),
                ('is_return_support', models.BooleanField(default=False, verbose_name='戻り対応')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mosaic_created_interactions', to=settings.AUTH_USER_MODEL)),
                ('credited_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mosaic_credited_interactions', to='accounts.member', verbose_name='実績扱い')),
                ('input_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mosaic_input_interactions', to='accounts.member', verbose_name='入力者')),
                ('service_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mosaic_service_interactions', to='accounts.member', verbose_name='接客者')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='mosaic.mosaicresulttype', verbose_name='結果')),
                ('trial_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='mosaic.mosaictrialmodel', verbose_name='お試しモデル')),
                ('visit_purpose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='mosaic.mosaicvisitpurpose', verbose_name='来店目的')),
            ],
            options={
                'ordering': ['-interaction_date', '-created_at', '-id'],
                'indexes': [models.Index(fields=['interaction_date'], name='mosaic_inter_date_idx'), models.Index(fields=['credited_member', 'interaction_date'], name='mosaic_inter_credit_idx'), models.Index(fields=['service_member', 'interaction_date'], name='mosaic_inter_service_idx'), models.Index(fields=['result', 'interaction_date'], name='mosaic_inter_result_idx')],
            },
        ),
    ]
