# Generated by Django 6.0.3 on 2026-08-06 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosaic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosaicinteraction',
            name='party_type',
            field=models.CharField(blank=True, choices=[('single', '1人'), ('pair', '2人'), ('group', 'それ以上')], max_length=16, verbose_name='人数区分'),
        ),
        migrations.CreateModel(
            name='MosaicInteractionTrialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_model_steps', to='mosaic.mosaicinteraction')),
                ('trial_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_steps', to='mosaic.mosaictrialmodel')),
            ],
            options={
                'ordering': ['step_order', 'id'],
                'unique_together': {('interaction', 'trial_model')},
            },
        ),
    ]
