# Generated by Django 6.0.3 on 2026-08-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosaic', '0002_alter_mosaicinteraction_party_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosaicinteraction',
            name='awareness_status',
            field=models.CharField(blank=True, choices=[('known', '認知あり'), ('unknown', '認知なし'), ('unconfirmed', '不明')], max_length=16, verbose_name='認知状況'),
        ),
    ]
