# Generated by Django 6.0.2 on 2026-02-23 07:25

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0004_department_default_reporter"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyDepartmentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(default=timezone.localdate)),
                ("total_count", models.PositiveIntegerField(default=0)),
                ("followup_count", models.PositiveIntegerField(default=0)),
                ("location", models.CharField(blank=True, max_length=128)),
                ("memo", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_reports",
                        to="accounts.department",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_reports",
                        to="accounts.member",
                    ),
                ),
            ],
            options={
                "ordering": ["-report_date", "-created_at"],
            },
        ),
    ]
