# Generated by Django 6.0.2 on 2026-02-23 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_department_default_reporter"),
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyDepartmentReportLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField(default=0)),
                ("count", models.PositiveIntegerField(default=0)),
                ("location", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_report_lines",
                        to="accounts.member",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="reports.dailydepartmentreport",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
