# Generated by Django 6.0.2 on 2026-02-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_dailydepartmentreportline'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydepartmentreportline',
            name='cs_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailydepartmentreportline',
            name='refugee_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
