# Generated by Django 6.0.8 on 2026-08-15 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_member_un_activity_code'),
        ('activity_sites', '0001_initial'),
        ('reports', '0005_replace_updated_at_with_edited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydepartmentreport',
            name='activity_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_reports', to='activity_sites.activitysite'),
        ),
        migrations.AddField(
            model_name='dailydepartmentreportline',
            name='activity_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_report_lines', to='activity_sites.activitysite'),
        ),
        migrations.AddIndex(
            model_name='dailydepartmentreport',
            index=models.Index(fields=['activity_site', 'report_date'], name='report_site_date_idx'),
        ),
        migrations.AddIndex(
            model_name='dailydepartmentreportline',
            index=models.Index(fields=['activity_site'], name='report_line_site_idx'),
        ),
    ]
