# Generated by Django 6.0.3 on 2026-05-14 04:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_member_email'),
        ('dairymetrics', '0008_default_existing_entry_sources_to_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberMetricTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_amount', models.PositiveIntegerField(default=0)),
                ('age_band', models.CharField(choices=[('teens', '10代'), ('twenties', '20代'), ('thirties', '30代'), ('forties', '40代'), ('fifties', '50代'), ('sixties', '60代'), ('seventies', '70代'), ('eighties', '80代'), ('nineties_or_older', '90代以上')], max_length=32)),
                ('is_student', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('male', '男性'), ('female', '女性')], max_length=16)),
                ('nationality_type', models.CharField(choices=[('domestic', '国内'), ('overseas', '海外')], max_length=16)),
                ('location', models.CharField(blank=True, max_length=128)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='dairymetrics.memberdailymetricentry')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentDailyMetricSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(default=django.utils.timezone.localdate)),
                ('approach_count', models.PositiveIntegerField(default=0)),
                ('communication_count', models.PositiveIntegerField(default=0)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('support_amount', models.PositiveIntegerField(default=0)),
                ('daily_target_count', models.PositiveIntegerField(default=0)),
                ('daily_target_amount', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_department_daily_metric_summaries', to='accounts.member')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metric_summaries', to='accounts.department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_department_daily_metric_summaries', to='accounts.member')),
            ],
            options={
                'ordering': ['-entry_date', 'department__code'],
                'constraints': [models.UniqueConstraint(fields=('department', 'entry_date'), name='unique_department_daily_metric_summary')],
            },
        ),
    ]
