# Generated by Django 6.0.3 on 2026-05-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dairymetrics", "0009_membermetrictransaction_departmentdailymetricsummary"),
    ]

    operations = [
        migrations.AddField(
            model_name="metricadjustment",
            name="location_name",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
