# Generated by Django 6.0.3 on 2026-05-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairymetrics', '0011_membermetrictransaction_wv_result_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdailymetricentry',
            name='daily_target_cs_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memberdailymetricentry',
            name='daily_target_refugee_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membermetrictransaction',
            name='wv_cs_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membermetrictransaction',
            name='wv_refugee_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='membermetrictransaction',
            name='wv_result_type',
            field=models.CharField(blank=True, choices=[('cs', 'CSのみ'), ('refugee', '難民のみ'), ('both', '両方')], max_length=16),
        ),
        migrations.AlterField(
            model_name='metricadjustment',
            name='source_type',
            field=models.CharField(choices=[('postal', '郵送'), ('qr', 'QR'), ('increase', '増額'), ('other', 'その他')], default='other', max_length=24),
        ),
    ]
