# Generated by Django 6.0.3 on 2026-06-23 03:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_member_un_activity_code'),
        ('dairymetrics', '0015_alter_metricadjustment_source_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WVMetricCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField(default=django.utils.timezone.localdate)),
                ('wv_result_type', models.CharField(choices=[('cs', 'CS'), ('refugee', '難民'), ('both', 'CS+難民')], default='cs', max_length=16)),
                ('wv_cs_count', models.PositiveIntegerField(default=0)),
                ('wv_refugee_amount', models.PositiveIntegerField(default=0)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('support_amount', models.PositiveIntegerField(default=0)),
                ('cs_count', models.PositiveIntegerField(default=0)),
                ('refugee_count', models.PositiveIntegerField(default=0)),
                ('age_band', models.CharField(blank=True, choices=[('teens', '10代'), ('twenties', '20代'), ('thirties', '30代'), ('forties', '40代'), ('fifties', '50代'), ('sixties', '60代'), ('seventies', '70代'), ('eighties', '80代'), ('nineties_or_older', '90代以上')], max_length=32)),
                ('is_student', models.BooleanField(default=False)),
                ('gender', models.CharField(blank=True, choices=[('male', '男性'), ('female', '女性')], max_length=16)),
                ('nationality_type', models.CharField(blank=True, choices=[('domestic', '国内'), ('overseas', '海外')], max_length=16)),
                ('location_name', models.CharField(blank=True, max_length=120)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wv_metric_cancellations', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wv_metric_cancellations', to='accounts.department')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wv_metric_cancellations', to='accounts.member')),
                ('original_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wv_cancellations', to='dairymetrics.membermetrictransaction')),
            ],
            options={
                'ordering': ['-target_date', '-created_at'],
            },
        ),
    ]
