# Generated by Django 6.0.3 on 2026-08-05 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_member_un_activity_code'),
        ('dairymetrics', '0017_memberdailymetricentry_activity_reminder_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberMetricTransactionReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('good', 'グッド'), ('nice', 'ナイス'), ('thanks', '感謝'), ('learn', '学び')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_transaction_reactions', to='accounts.member')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='dairymetrics.membermetrictransaction')),
            ],
            options={
                'ordering': ['transaction_id', 'member__name'],
                'constraints': [models.UniqueConstraint(fields=('transaction', 'member'), name='unique_metric_transaction_member_reaction')],
            },
        ),
    ]
