# Generated by Django 6.0.8 on 2026-08-15 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_member_un_activity_code'),
        ('activity_sites', '0001_initial'),
        ('dairymetrics', '0020_membermetrictransactionnotificationstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdailymetricentry',
            name='activity_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_entries', to='activity_sites.activitysite'),
        ),
        migrations.AddField(
            model_name='memberdailymetricentry',
            name='activity_site_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_entries', to='activity_sites.activitysiteproposal'),
        ),
        migrations.AddField(
            model_name='membermetrictransaction',
            name='activity_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_transactions', to='activity_sites.activitysite'),
        ),
        migrations.AddField(
            model_name='metricadjustment',
            name='activity_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_adjustments', to='activity_sites.activitysite'),
        ),
        migrations.AddField(
            model_name='wvmetriccancellation',
            name='activity_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_cancellations', to='activity_sites.activitysite'),
        ),
        migrations.AddIndex(
            model_name='memberdailymetricentry',
            index=models.Index(fields=['activity_site', 'department', 'entry_date'], name='dm_site_dept_date_idx'),
        ),
        migrations.AddIndex(
            model_name='membermetrictransaction',
            index=models.Index(fields=['activity_site', 'created_at'], name='dm_site_tx_created_idx'),
        ),
        migrations.AddIndex(
            model_name='metricadjustment',
            index=models.Index(fields=['activity_site', 'target_date'], name='dm_site_adj_date_idx'),
        ),
        migrations.AddIndex(
            model_name='wvmetriccancellation',
            index=models.Index(fields=['activity_site', 'target_date'], name='dm_site_cancel_date_idx'),
        ),
    ]
