# Generated by Django 6.0.2 on 2026-03-05 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('legacy_product_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('video_url', models.URLField(blank=True)),
                ('testimonied_at', models.DateField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('legacy_article_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('migrated_at', models.DateTimeField(blank=True, null=True)),
                ('migration_source', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimony_articles', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='testimony.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='testimony.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimony_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'article'), name='testimony_unique_favorite')],
            },
        ),
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='testimony.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimony_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'article'), name='testimony_unique_like')],
            },
        ),
        migrations.CreateModel(
            name='ArticleViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_viewed_at', models.DateTimeField()),
                ('last_viewed_at', models.DateTimeField()),
                ('view_count', models.PositiveIntegerField(default=1)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_histories', to='testimony.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimony_view_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-last_viewed_at'], name='testimony_a_user_id_4266a6_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'article'), name='testimony_unique_view_history')],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['testimonied_at'], name='testimony_a_testimo_7b06f5_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['product'], name='testimony_a_product_4de49a_idx'),
        ),
    ]
