# Generated by Django 6.0.3 on 2026-06-22 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_member_un_activity_code'),
        ('testimony', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimony_articles', to='accounts.department', verbose_name='部署'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=255, verbose_name='証者・投稿者名'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='article',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='testimony.product', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='article',
            name='testimonied_at',
            field=models.DateField(blank=True, null=True, verbose_name='証日'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='article',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='動画URL'),
        ),
    ]
