# Generated by Django 6.0.3 on 2026-06-22 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimony', '0002_article_department_alter_article_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': '商材', 'verbose_name_plural': '商材'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='department',
        ),
        migrations.AlterField(
            model_name='article',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='testimony.product', verbose_name='商材'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='商材名'),
        ),
    ]
