# Generated by Django 6.0.2 on 2026-03-04 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_member_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeReactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('label', models.CharField(max_length=64)),
                ('icon_class', models.CharField(default='fa-solid fa-circle', max_length=128)),
                ('color', models.CharField(default='#126e82', max_length=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('author_name_snapshot', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('draft', '下書き'), ('published', '公開'), ('archived', 'アーカイブ')], default='published', max_length=16)),
                ('is_deleted', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_posts', to='accounts.member')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgePostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_tags', to='talks.knowledgepost')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_posts', to='talks.knowledgetag')),
            ],
        ),
        migrations.AddField(
            model_name='knowledgepost',
            name='tags',
            field=models.ManyToManyField(related_name='posts', through='talks.KnowledgePostTag', to='talks.knowledgetag'),
        ),
        migrations.CreateModel(
            name='KnowledgeUserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_tags', models.ManyToManyField(blank=True, related_name='preferred_by_users', to='talks.knowledgetag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name_snapshot', models.CharField(blank=True, max_length=64)),
                ('body', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_comments', to='accounts.member')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='talks.knowledgecomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='talks.knowledgepost')),
                ('reaction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='talks.knowledgereactiontype')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['post', 'created_at'], name='talks_knowl_post_id_9ed92d_idx'), models.Index(fields=['post', 'reaction_type', 'created_at'], name='talks_knowl_post_id_7ebf1d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('id', models.F('parent')), _negated=True), name='knowledge_comment_parent_not_self')],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgeposttag',
            index=models.Index(fields=['tag', 'post'], name='talks_knowl_tag_id_a44839_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='knowledgeposttag',
            unique_together={('post', 'tag')},
        ),
        migrations.AddIndex(
            model_name='knowledgepost',
            index=models.Index(fields=['status', '-updated_at'], name='talks_knowl_status_bfb934_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgepost',
            index=models.Index(fields=['-created_at'], name='talks_knowl_created_1ecbd2_idx'),
        ),
    ]
