# Generated by Django 6.0.3 on 2026-03-09 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0003_knowledgepostfavorite'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='knowledgepostfavorite',
            new_name='talks_knowl_user_id_10378b_idx',
            old_name='talks_knowl_user_id_2f9e6f_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgepostfavorite',
            new_name='talks_knowl_post_id_a3f610_idx',
            old_name='talks_knowl_post_id_8e8196_idx',
        ),
    ]
